# Exported from Render on 2026-09-06T13:31:05Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: booking-n8n
      runtime: image
      image:
        url: docker.io/n8nio/n8n:1.121.1
      plan: free
      envVars:
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: DB_POSTGRESDB_USER
        sync: false
      - key: DB_POSTGRESDB_PORT
        sync: false
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: DB_POSTGRESDB_HOST
        sync: false
      - key: DB_POSTGRESDB_DATABASE
        sync: false
      - key: N8N_PROTOCOL
        sync: false
      - key: DB_POSTGRESDB_SCHEMA
        sync: false
      - key: GENERIC_TIMEZONE
        sync: false
      - key: TZ
        sync: false
      - key: N8N_ENCRYPTION_KEY
        sync: false
      - key: DB_TYPE
        sync: false
      region: oregon
      autoDeployTrigger: commit
