name: Deploy Dev

on:
  push:
    branches:
      - dev   # this workflow only runs when pushing to dev branch

# env:
  # DEPLOYMENT_PLATFORM: ${{ vars.DEPLOYMENT_PLATFORM }}

jobs:
  lint-portfolio:
    name: Lint Portfolio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use NodeJS v22.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0
      - name: Install Dependencies and lint
        run: |
          npm install
          npm run lint

  deploy-dev-vercel:
    name: Deploy Portfolio to Vercel
    needs: lint-portfolio
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_APP: ${{ secrets.VERCEL_APP_DEV }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          mkdir "$VERCEL_APP"
          vercel pull \
            --cwd "$VERCEL_APP" \
            --yes \
            --environment=preview \
            --token="$VERCEL_TOKEN"

      - name: Build Project Artifacts
        run: |
          mv "$VERCEL_APP/.vercel" .
          npm install
          vercel build --token="$VERCEL_TOKEN"

      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel deploy \
            --prebuilt \
            --token="$VERCEL_TOKEN"

      - name: Post Deployment Clean-up
        run: |
          rm -rf .vercel
          rm -rf "$VERCEL_APP"