name: Deploy Dev

on:
  push:
    branches:
      - dev   # this workflow only runs when pushing to dev branch

# env:
  # DEPLOYMENT_PLATFORM: ${{ vars.DEPLOYMENT_PLATFORM }}

jobs:
  lint-portfolio:
    name: Lint Portfolio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use NodeJS v22.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0
      - name: Install Dependencies and lint
        run: 
          npm install
          npm run lint

  deploy-dev-vercel:
    name: Deploy to Vercel Preview
    needs: lint-portfolio
    runs-on: ubuntu-latest
    environment: Preview
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_APP: ${{ secrets.VERCEL_APP}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Vercel CLI
        run: npm install --global vercel@28.16.7
      
      - name: Check VERCEL_TOKEN present
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "NO_TOKEN"
            exit 1
          else
            echo "TOKEN_PRESENT"
          fi


      - name: Pull Vercel Environment Information
        run: |
          mkdir $VERCEL_APP
          vercel pull --cwd $VERCEL_APP --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel Preview
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
